02_Django_Exercises/My_site/blog/urls.py
from django.urls import path
from blog.views import *

app_name="blog"

urlpatterns = [
    path("", blog_view, name="index"),
    path("<int:pid>", blog_single, name="single"),
    path("category/<str:cat_name>", blog_view, name="category"),
    path("tag/<str:tag_name>", blog_view, name="tag"),
    path("author/<str:username>", blog_view, name="author"),
    path("search/", blog_search, name="search"),
]

02_Django_Exercises/My_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls


sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls")),
    path("blog/", include("blog.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", include('robots.urls')),
    
] + debug_toolbar_urls()

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

02_Django_Exercises/My_site/website/urls.py
from django.urls import path
from website.views import *

app_name="website"

urlpatterns = [
    path("", home_view, name="index"),
    path("contact", contact_view, name="contact"),
    path("about", about_view, name="about"),
    path("test", test_view, name="test"),
    path("newsletter", newsletter_view, name="newsletter"),
    
]

02_Django_Exercises/My_site/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class Category(models.Model):
    name = models.CharField(max_length= 255)

    def __str__(self):
        return self.name
class Post(models.Model):
    author = models.ForeignKey(User, on_delete= models.SET_NULL, null= True)
    image = models.ImageField(upload_to= 'blog/', default= 'blog/default.jpg')
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ManyToManyField(Category)
    tags = TaggableManager()
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid': self.id})
    

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=255)
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        
        ordering = ['-created_date']
    def __str__(self):
        return self.name

02_Django_Exercises/My_site/website/models.py
from django.db import models
from django.utils import timezone

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.subject or 'No Subject'
    
class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

02_Django_Exercises/My_site/blog/forms.py
from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['name', 'email', 'subject', 'message']

02_Django_Exercises/My_site/website/forms.py
from django import forms
from website.models import Contact, Newsletter
from captcha.fields import CaptchaField

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Contact
        fields = '__all__'

class NewsletterForm(forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = '__all__'

02_Django_Exercises/My_site/blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post, Comment
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from blog.forms import CommentForm
from django.contrib import messages


def blog_view(request, **kwargs):
    posts = Post.objects.filter(published_date__lte=timezone.now(), status = 1)
    
    if kwargs.get('cat_name') != None :
        posts = posts.filter(category__name=kwargs.get('cat_name'))

    if kwargs.get('username') != None :
        posts = posts.filter(author__username=kwargs.get('username'))

    if kwargs.get('tag_name') != None :
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])

    posts = Paginator(posts, 3)

    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)

    except PageNotAnInteger:
        posts = posts.get_page(1)
    
    except EmptyPage:
        posts = posts.get_page(1)
        
    context = {'posts': posts}
    return render(request, "blog/blog-home.html", context)


def blog_single(request, pid):
    posts = get_object_or_404(Post, pk=pid, status=1)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = posts 
            form.save()
            messages.success(request, "Your Comment submited Succsessfuly!")
        else:
            messages.error(request, "Your Comment didnt submit!")

    prev_post = Post.objects.filter(id__lt=posts.id).order_by('-id').first()
    next_post = Post.objects.filter(id__gt=posts.id).order_by('id').first()

    comments = Comment.objects.filter(post=posts.id, approved=True)
    form = CommentForm()

    context = {'posts': posts, 'comments': comments, 'form': form, 'prev_post': prev_post, 'next_post': next_post}
    return render(request, "blog/blog-single.html", context)


def blog_category(request, cat_name):
    posts = Post.objects.filter(status=1)
    posts = posts.filter(category__name=cat_name)
    context = {'posts': posts}
    return render(request, "blog/blog-home.html", context)

def blog_search(request):
    posts = Post.objects.filter(published_date__lte=timezone.now(), status = 1)

    if request.method == 'GET':
        if srch := request.GET.get('s'):
            posts = posts.filter(content__contains=srch)
    
    context = {'posts': posts}
    return render(request, "blog/blog-home.html",context)

02_Django_Exercises/My_site/website/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from website.forms import   ContactForm, NewsletterForm
from django.contrib import messages


def home_view(request):
    return render(request, "website/index.html")


def contact_view(request):
    if request.method =='POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.name = ticket.name.title()
            ticket.save()
            messages.success(request, "Your ticket submited Succsessfuly!")
        else:
            messages.error(request, "Your ticket didnt submit!")

    form = ContactForm()
    return render(request, "website/contact.html", {'form': form})

def newsletter_view(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        HttpResponse('not valid')


def about_view(request):
    return render(request, "website/about.html")


def test_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('done')
        else:
            return HttpResponse('not valid')

    form = ContactForm()
    return render(request, "test.html", {'form':form})

02_Django_Exercises/My_site/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Travel</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
			CSS
			============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>

<body>
    <header id="header">
        <div class="header-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                        <ul>
                            <li><a href="#">Visit Us</a></li>
                            <li><a href="#">Buy Tickets</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 col-sm-6 col-6 header-top-right">
                        <div class="header-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo">
                    <a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li><a href="{% url 'website:index' %}">Home</a></li>
                        <li><a href="{% url 'website:about' %}">About</a></li>
                        <li><a href="{% url 'blog:index' %}">Blog</a></li>

                        <li class="menu-has-children"><a href="">Pages</a>
                            <ul>
                                <li><a href="elements.html">Elements</a></li>
                                <li class="menu-has-children"><a href="">Level 2 </a>
                                    <ul>
                                        <li><a href="#">Item One</a></li>
                                        <li><a href="#">Item Two</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="{% url 'website:contact' %}">Contact</a></li>
                    </ul>
                </nav><!-- #nav-menu-container -->
            </div>
        </div>
    </header><!-- #header -->


    {% block content %}



    {% endblock %}


    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container">

            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Agency</h6>
                        <p>
                            The world has become so fast paced that people don’t want to stand by reading a page of
                            information, they would much rather look at a presentation and understand the message. It
                            has come to a point
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Navigation Links</h6>
                        <div class="row">
                            <div class="col">
                                <ul>
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Feature</a></li>
                                    <li><a href="#">Services</a></li>
                                    <li><a href="#">Portfolio</a></li>
                                </ul>
                            </div>
                            <div class="col">
                                <ul>
                                    <li><a href="#">Team</a></li>
                                    <li><a href="#">Pricing</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>
                            For business professionals caught between high OEM price and mediocre print and graphic
                            output.
                        </p>
                        <div>
                            <form
                                action="{% url 'website:newsletter' %}"
                                method="post" class="subscription relative">
                                {% csrf_token %}
                                <div class="input-group d-flex flex-row">
                                    <input name="email" placeholder="Email Address" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Email Address '" required="" type="email">
                                    <button class="btn bb-btn" type="submit"><span class="lnr lnr-location"></span></button>
                                </div>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">InstaFeed</h6>
                        <ul class="instafeed d-flex flex-wrap">
                            <li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row footer-bottom d-flex justify-content-between align-items-center">
                <p class="col-lg-8 col-sm-12 footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is
                    made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                        target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
                <div class="col-lg-4 col-sm-12 footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-behance"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->

    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

02_Django_Exercises/My_site/templates/blog/blog-ads-widget.html
{% load static %}

<div class="single-sidebar-widget ads-widget">
						<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
					</div>

02_Django_Exercises/My_site/templates/blog/blog-category-widget.html
{% load static %}

<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for cat in categories %}
        <li>
            <a href="{% url 'blog:category' cat_name=cat.name %}" class="d-flex justify-content-between">
                <p>{{cat.name}}</p>
                <p>{{cat.count}}</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

02_Django_Exercises/My_site/templates/blog/blog-cloud-tags.html
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>

            {% for tag in posts.tags.all %}
                <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a></li>
            {% endfor %}

    </ul>
</div> 

02_Django_Exercises/My_site/templates/blog/blog-latest-posts.html
{% load humanize %}
{% load static %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{post.image.url}}" alt="">
            </div>
            <div class="details">
                <a href="{% url 'blog:single' pid=post.id %}"><h6>{{post.title}}</h6></a>
                <p>{{post.published_date|naturaltime}}</p>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

02_Django_Exercises/My_site/templates/blog/blog-search.html
{% load static %}

<div class="col-lg-4 sidebar-widgets">
    <div class="widget-wrap">
        <div class="single-sidebar-widget search-widget">
            <form class="search-form" action="{% url 'blog:search' %}" method="get">
                <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Search Posts'">
                <button type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div>

02_Django_Exercises/My_site/templates/blog/blog-single.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% load humanize %}

{% block content %}

<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{posts.title}}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span
						class="lnr lnr-arrow-right"></span> {{posts.title}}</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{{posts.image.url}}" alt="">
						</div>
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in posts.category.all %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a> {% if not forloop.last %},{% endif %}</li>
							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{posts.author.get_full_name}}</a> <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{posts.published_date|date:"d, M, Y"}}</a> <span
									class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{posts.counted_views}} Views</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments|length}} Comments</a> <span
									class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{posts.title}}</h3>
						<p class="excert">
							{{posts.content|safe}}
						</p>
					</div>
				</div>
				<div class="navigation-area">
					<div class="row">
						<div
							class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								<a href="#"><img class="img-fluid" src="{% static 'img/blog/prev.jpg' %}" alt=""></a>
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								{% if prev_post %}
								<p>Prev Post</p>
								<a href="{% url 'blog:single' prev_post.id %}">
									<h4>{{ prev_post.title }}</h4>
								</a>
								{% else %}
								<a href="#">
									<h4>There is no prev post</h4>
								</a>
								{% endif %}
							</div>
						</div>
						<div
							class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Next Post</p>
								{% if next_post %}
								<a href="{% url 'blog:single' next_post.id %}">
									<h4>{{ next_post.title }}</h4>
								</a>
								{% else %}
								<a href="#">
									<h4>There is no next post</h4>
								</a>
								{% endif %}
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								<a href="#"><img class="img-fluid" src="{% static 'img/blog/next.jpg' %}" alt=""></a>
							</div>
						</div>
					</div>
				</div>
				<div class="comments-area">

					<h4>{{comments|length}} Comments</h4>
					<div class="comment-list">
						{% for comment in comments %}
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c1.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a>{{comment.name}}</a></h5>
									<p class="date">{{comment.created_date|naturalday}} </p>
									<p class="comment">
										{{comment.message}}
									</p>
								</div>
							</div>
							<!--
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
							-->
						</div>
						{% empty %}
						<p>There is no comment here. be the first one!</p>

						{% endfor %}
					</div>
				</div>
				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form method="post" action='{% url "blog:single" pid=posts.id %}'>
						{% csrf_token %}
						<input type="hidden" name="post" value={{posts.id}}>

						<div class="form-group form-inline">
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" name="name" placeholder="Enter Name"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" name="email" placeholder="Enter email address"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>
						</div>
						<div class="form-group">
							<input type="text" class="form-control" name="subject" placeholder="Subject"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
								required=""></textarea>
						</div>
						<button class="primary-btn text-uppercase" type="submit">Post Comment</button>
					</form>
				</div>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					<div class="single-sidebar-widget search-widget">
						<form class="search-form" action="#">
							<input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Search Posts'">
							<button type="submit"><i class="fa fa-search"></i></button>
						</form>
					</div>
					{% if messages %}
					<div style="position: fixed; top: 20px; right: 20px; z-index: 9999;">
					{% for message in messages %}
					<div class="alert alert-success alert-dismissible fade show" role="alert" 
						style="width: 250px; padding: 0.5rem 1rem; font-size: 0.9rem; position: relative;">
						{{ message }}
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"
								style="position: absolute; top: 5px; right: 5px;"></button>
					</div>
					{% endfor %}
					</div>

					<script>
					setTimeout(() => {
						document.querySelectorAll('.alert').forEach(alert => {
						alert.classList.remove('show');
						alert.classList.add('fade');
						setTimeout(() => alert.remove(), 500);
						});
					}, 4000);
					</script>
					{% endif %}
					
					
					{% if form.errors %}
						<div class="alert alert-error">
						<h4>Please fix the following errors</h4>
						<ul>
							{% for field in form %}
							{% if field.errors %}
								{% for error in field.errors %}
								<li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
								{% endfor %}
							{% endif %}
							{% endfor %}
						</ul>
						{% if form.non_field_errors %}
							{{ form.non_field_errors }}
						{% endif %}
						</div>
					{% endif %}
					
					{% include 'blog/blog-writer.html' %}

					{% latestposts 2 %}

					{% include 'blog/blog-ads-widget.html' %}

					{% categories %}

					{% include 'blog/blog-newsletter.html' %}
					
					{% include "blog/blog-cloud-tags.html" %}	


				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->

{% endblock %}

02_Django_Exercises/My_site/templates/test.html
{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>form test</title>
</head>
<body>

    <form action="{% url 'website:test' %}" method="post">
        {% csrf_token %}

        {{form.as_p}}
        <button type="submit">submit</button>
    </form>

</body>
</html>